// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5QtlOp3kaKZ-S17G1FOWj4ZVHllSFQDk',
    appId: '1:739489456051:web:52d136e98824a46d50f5c6',
    messagingSenderId: '739489456051',
    projectId: 'flutterfire-ui-codelab-af676',
    authDomain: 'flutterfire-ui-codelab-af676.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-af676.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjEbJKXTd6VjJMlYLjvhjrt6RUJHdwgqw',
    appId: '1:739489456051:android:ffb5fa8a5e9fc0c450f5c6',
    messagingSenderId: '739489456051',
    projectId: 'flutterfire-ui-codelab-af676',
    storageBucket: 'flutterfire-ui-codelab-af676.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTIce8blrM5znCvjYkI9NgtuLEdPNt5Wk',
    appId: '1:739489456051:ios:7e4cd7349189ce9250f5c6',
    messagingSenderId: '739489456051',
    projectId: 'flutterfire-ui-codelab-af676',
    storageBucket: 'flutterfire-ui-codelab-af676.appspot.com',
    iosClientId: '739489456051-e4mn4g7pf1cs7gehrvf4gt3f0pr015om.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTIce8blrM5znCvjYkI9NgtuLEdPNt5Wk',
    appId: '1:739489456051:ios:7e4cd7349189ce9250f5c6',
    messagingSenderId: '739489456051',
    projectId: 'flutterfire-ui-codelab-af676',
    storageBucket: 'flutterfire-ui-codelab-af676.appspot.com',
    iosClientId: '739489456051-e4mn4g7pf1cs7gehrvf4gt3f0pr015om.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
